In [10]:
import numpy as np
ar = np.arange(1,101)
square = ar ** 2
print(ar)
print (square)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[    1     4     9    16    25    36    49    64    81   100   121   144
   169   196   225   256   289   324   361   400   441   484   529   576
   625   676   729   784   841   900   961  1024  1089  1156  1225  1296
  1369  1444  1521  1600  1681  1764  1849  1936  2025  2116  2209  2304
  2401  2500  2601  2704  2809  2916  3025  3136  3249  3364  3481  3600
  3721  3844  3969  4096  4225  4356  4489  4624  4761  4900  5041  5184
  5329  5476  5625  5776  5929  6084  6241  6400  6561  6724  6889  7056
  7225  7396  7569  7744  7921  8100  8281  8464  8649  8836  9025  9216
  9409  9

In [11]:
players= np.array(["sachin" , "virat" , "rohit" , "yuvraj"])
matches=np.array(["IPL2025", "IPL2021", "IPL2020"])
np.random.seed(42)

runs=np.random.randint(10,100,size =(len(players), len(matches)))
print(players)
print(matches)
print(runs)

['sachin' 'virat' 'rohit' 'yuvraj']
['IPL2025' 'IPL2021' 'IPL2020']
[[61 24 81]
 [70 30 92]
 [96 84 84]
 [97 33 12]]


In [13]:
import numpy as np

np.random.seed(10)

# Generate data for 10 employees
age = np.random.randint(22, 36, 10)
sales = np.random.randint(40, 71, 10)
working_hours = np.random.choice([40, 42, 45], 10)
performance = np.random.choice([7, 8, 9], 10)

# Combine columns to create dataset
dataset = np.column_stack((age, sales, working_hours, performance))

print("Employee Dataset:")
print(dataset) 

sales = dataset[:, 1]

# Mean
mean = np.mean(sales)

# Median
median = np.median(sales)

# Standard Deviation
std = np.std(sales)

# Mode
values, counts = np.unique(sales, return_counts=True)
mode = values[np.argmax(counts)]

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Standard Deviation:", std)

Employee Dataset:
[[31 69 40  8]
 [35 57 40  9]
 [26 66 45  8]
 [22 48 40  8]
 [23 49 45  8]
 [33 40 45  8]
 [34 50 42  9]
 [31 48 40  8]
 [35 62 40  7]
 [22 44 45  9]]
Mean: 53.3
Median: 49.5
Mode: 48
Standard Deviation: 9.198369420718


In [19]:
import numpy as np

# Create a 4x4 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print("2D Array:")
print(arr)

# Average of each row
row_avg = np.mean(arr, axis=1)
print("\nAverage of each row:")
print(row_avg)

# Average of each column
column_avg = np.mean(arr, axis=0)
print("\nAverage of each column:")
print(column_avg)

# Standard deviation of the entire array
std = np.std(arr)
print("\nStandard Deviation:")
print(std)

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Average of each row:
[ 2.5  6.5 10.5 14.5]

Average of each column:
[ 7.  8.  9. 10.]

Standard Deviation:
4.6097722286464435
